love.graphics.setDefaultFilter("nearest", "nearest")

grass = love.graphics.newImage("tile/grass.png")
underbrush = love.graphics.newImage("tile/underbrush.png")
sand = love.graphics.newImage("tile/sand.png")
water = love.graphics.newImage("tile/water.png")
farm_empty = love.graphics.newImage("tile/farm.png")
forest_tree = love.graphics.newImage("tile/forest_tree.png")
jungle_tree = love.graphics.newImage("tile/jungle_tree.png")
berry_bush = love.graphics.newImage("tile/berry_bush.png")
farm_wheat_seeds = love.graphics.newImage("tile/farm_wheat_seeds.png")
farm_wheat_grown = love.graphics.newImage("tile/farm_wheat_grown.png")
cim = love.graphics.newImage("tile/cim.png")
wood_house = love.graphics.newImage("tile/wood_house.png")
dirt_road = love.graphics.newImage("tile/dirt_road.png")
stone_road = love.graphics.newImage("tile/stone_road.png")